apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-java-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-java-demo
  template:
    metadata:
      labels:
        app: jenkins-java-demo
    spec:
      containers:
      - name: jenkins-java-demo
        image: {image}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-java-demo-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: jenkins-java-demo
  selector:
    app: jenkins-java-demo
  type: LoadBalancer

---
apiVersion: v1
kind: Ingress
metadata:
  name: jenkins-java-demo-ingress
spec:
  rules:
  - host: test.yilingyi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-java-demo-svc
          servicePort: 80
